---
title: "Event Template"
author: "Mike Xiao"
date: "9/24/2019"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 6
    toc_float: true
---


# [Default Events]----------------------------------------------------------------------------------------

## [Clinical Case]

<br>

### **M/D/YYYY - Clinical Case**

**Presenters: [NAMES]**

**Time: N/A**

**Location: N/A**

*Description: N/A*

*Calendar Link: N/A*

<br>

- - - 

## [Graduate School]

<br>

### **M/D/YYYY - Graduate School: [TITLE]**

**Presenters: [NAMES]**

**Time: N/A**

**Location: N/A**

*Description: N/A*

*Calendar Link: N/A*

<br>

- - - 

## [Mindfulness]

<br>

### **M/D/YYYY - Mindfulness**

**Presenters: [NAMES]**

**Time: N/A**

**Location: N/A**

*Description: N/A*

*Calendar Link: N/A*

<br>

- - - 

## [Protocol Review] 

<br>

### **M/D/YYYY - Protocol Review: [TITLE]**

**Presenters: [NAMES]**

**Time: N/A**

**Location: N/A**

*Description: N/A*

*Calendar Link: N/A*

<br>

- - - 

## [Statistical Methods]

<br>

### **M/D/YYYY - Statistical Methods**

**Presenters: [NAMES]**

**Time: N/A**

**Location: N/A**

*Description: N/A*

*Calendar Link: N/A*

<br>

- - - 

# [Abnormal Events]--------------------------------------------------------------------------------------

## [Cancelled Event]

<br>

### **M/D/YYYY - (Cancelled)**

**Presenters: N/A**

**Time: N/A**

**Location: N/A**

*Description: Session is cancelled this week.*

*Calendar Link: N/A*

<br>

- - - 

## [Rescheduled Event]

<br>

### **M/D/YYYY - [TITLE] (Rescheduled)**

**Presenters: N/A**

**Time: N/A**

**Location: N/A**

*Description: This event needs to be rescheduled.*

*Calendar Link: N/A*

<br>

- - -

## [AllStaff Meeting]

<br>

### **M/D/YYYY - CMI AllStaff Meeting**

**Presenters: N/A**

**Time: N/A**

**Location: N/A**

*Description: This is an all staff meeting.*

*Calendar Link: N/A*

<br>

- - -

